[workspace]
members = [
    "classgroup",
    "curve-abstract",
    "rug-1.27.0",
    "secp256k1-sys",
    "svarog-curve25519",
    "svarog-secp256k1",
]
resolver = "3"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
strip = true
