[package]
name = "classgroup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
once_cell = "1.21.3"
rug = { path = "../rug-1.27.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde-pickle = "1.2.0"
